--- #YAML:1.0
name:               Crane
version:            1.00.0001
abstract:           ~
author:
    - Tema Novikov <novikov.tema@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Carp:                 0
    Cwd:                  0
    English:              0
    File::Basename:       0
    File::Spec::Functions:  0
    IO::Handle:           0
    Readonly:             0
requires:
    perl:  
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
